export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_UPDATE_SUCCESS = 'REGISTER_UPDATE_SUCCESS';
export const REGISTER_CREATE_SUCCESS = 'REGISTER_CREATE_SUCCESS';

export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
