version: '3.8'

services:
  backend:
    # Se o backend já tiver imagem ou Dockerfile próprio
    build: ./pasta-do-seu-backend
    ports:
      - '3001:3001' # Porta que a sua API usa
    networks:
      - minha-rede

  frontend:
    build: .
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules # Evita que o volume sobrescreva os pacotes do container
    environment:
      - VITE_API_URL=http://localhost:3001 # O segredo está aqui
    depends_on:
      - backend
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
